version: "2.2"
services:
  planner:
    build:
      context: ./planner
    image: planner
    container_name: planner
    ports:
     - "3000:3000"
    networks:
      - localh
    depends_on: 
      - worker
      - worker2
    environment: 
      - TASKS=4
  worker:
    build:
      context: ./worker
    image: worker
    container_name: worker
    ports:
     - "8080:8080"
    networks:
      - localh
    environment: 
      - MULT=true
      - PORT=8080
  worker2:
    build:
      context: ./worker
    image: worker
    container_name: worker2
    ports:
     - "8081:8081"
    networks:
      - localh
    environment: 
      - ADD=true
      - PORT=8081
networks:
  localh:
    driver: bridge